export const FETCH_INGREDIENT_PENDING = 'FETCH_INGREDIENT_PENDING';
export const FETCH_INGREDIENT_REJECTED = 'FETCH_INGREDIENT_REJECTED';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const REMOVE_ALL_INGREDIENTS = 'REMOVE_ALL_INGREDIENTS';
export const UPDATE_INGREDIENTS_TOTAL_NUTRITION = 'UPDATE_INGREDIENTS_TOTAL_NUTRITION';
export const REMOVE_ALL_INGREDIENTS_TOTAL_NUTRITION = 'REMOVE_ALL_INGREDIENTS_TOTAL_NUTRITION';
export const SAVE_RECIPE = 'SAVE_RECIPE';